# Generated by Django 3.2.15 on 2022-09-22 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_plugin_evpn', '0002_alter_evpnservice_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evpnservice',
            old_name='description',
            new_name='descr',
        ),
    ]
