# Generated by Django 3.2.15 on 2022-09-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_plugin_evpn', '0003_rename_description_evpnservice_descr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evpnservice',
            old_name='descr',
            new_name='description',
        ),
    ]
