# Generated by Django 3.2.15 on 2022-09-23 03:28

from django.db import migrations, models
import nautobot.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_plugin_evpn', '0004_rename_descr_evpnservice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='evpnservice',
            name='slug',
            field=nautobot.core.fields.AutoSlugField(blank=True, max_length=100, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='evpnservice',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
