# Generated by Django 3.2.15 on 2022-09-29 02:05

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nautobot.extras.models.mixins
import taggit.managers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0047_enforce_custom_field_slug'),
        ('ipam', '0008_prefix_vlan_vlangroup_location'),
        ('nautobot_plugin_evpn', '0006_auto_20220929_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evpnservice',
            options={'ordering': ['vni'], 'verbose_name': 'EVPN Service', 'verbose_name_plural': 'EVPN Services'},
        ),
        migrations.CreateModel(
            name='VNI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('vni', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16777216)])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'VXLAN VNI',
                'verbose_name_plural': 'VXLAN VNIs',
                'ordering': ['vni'],
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
        migrations.CreateModel(
            name='EVPNLayer3VRF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('type', models.CharField(max_length=20)),
                ('encapsulation', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('vni', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='nautobot_plugin_evpn.vni')),
                ('vrf', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='ipam.vrf')),
            ],
            options={
                'verbose_name': 'EVPN Layer 3 VRF',
                'verbose_name_plural': 'EVPN Layer 3 VRFs',
                'ordering': ['vrf'],
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
        migrations.CreateModel(
            name='EVPNLayer2VRF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('type', models.CharField(max_length=20)),
                ('encapsulation', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('vrf', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='ipam.vrf')),
            ],
            options={
                'verbose_name': 'EVPN Layer 2 VRF',
                'verbose_name_plural': 'EVPN Layer 2 VRFs',
                'ordering': ['vrf'],
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
        migrations.AddField(
            model_name='evpnservice',
            name='layer2_vrf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='nautobot_plugin_evpn.evpnlayer2vrf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evpnservice',
            name='layer3_vrf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='nautobot_plugin_evpn.evpnlayer3vrf'),
        ),
        migrations.AddField(
            model_name='evpnservice',
            name='vni',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.RESTRICT, to='nautobot_plugin_evpn.vni'),
            preserve_default=False,
        ),
    ]
