# Generated by Django 3.2.15 on 2022-09-30 02:59

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import nautobot.extras.models.mixins
import taggit.managers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0047_enforce_custom_field_slug'),
        ('dcim', '0014_location_status_data_migration'),
        ('nautobot_plugin_evpn', '0007_auto_20220929_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVPNAttachmentPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('descriptions', models.CharField(blank=True, max_length=200)),
                ('evpn_service', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='nautobot_plugin_evpn.evpnservice')),
                ('interface', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='dcim.interface')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'EVPN Attachment Point',
                'verbose_name_plural': 'EVPN Attachment Points',
                'ordering': ['evpn_service'],
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
    ]
