# Generated by Django 3.2.15 on 2022-09-30 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_plugin_evpn', '0008_evpnattachmentpoint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evpnattachmentpoint',
            old_name='descriptions',
            new_name='description',
        ),
    ]
