# Generated by Django 3.2.15 on 2022-10-03 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0014_location_status_data_migration'),
        ('nautobot_plugin_evpn', '0009_rename_descriptions_evpnattachmentpoint_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='evpnattachmentpoint',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='dcim.device'),
            preserve_default=False,
        ),
    ]
