# Generated by Django 3.2.15 on 2022-10-03 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_plugin_evpn', '0010_evpnattachmentpoint_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evpnattachmentpoint',
            name='evpn_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nautobot_plugin_evpn.evpnservice'),
        ),
    ]
