# Generated by Django 3.2.15 on 2022-10-07 02:31

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import nautobot.extras.models.mixins
import taggit.managers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0047_enforce_custom_field_slug'),
        ('nautobot_plugin_evpn', '0012_evpnlayer3interface'),
    ]

    operations = [
        migrations.CreateModel(
            name='EVPNEthernetSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('type', models.IntegerField(max_length=20)),
                ('esi', models.CharField(blank=True, max_length=29, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'EVPN Ethernet Segment Identifier',
                'verbose_name_plural': 'EVPN Segment Identifiers',
                'ordering': ['esi'],
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
    ]
