# Generated by Django 3.2.15 on 2022-10-07 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_plugin_evpn', '0013_evpnethernetsegment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evpnethernetsegment',
            name='esi',
            field=models.CharField(blank=True, default=None, max_length=29, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='evpnethernetsegment',
            name='type',
            field=models.IntegerField(),
        ),
    ]
