# Generated by Django 3.2.15 on 2022-10-18 02:13

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nautobot.extras.models.mixins
import taggit.managers
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0047_enforce_custom_field_slug'),
        ('dcim', '0014_location_status_data_migration'),
        ('nautobot_plugin_evpn', '0014_auto_20221007_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evpnethernetsegment',
            name='esi',
            field=models.CharField(blank=True, default=None, max_length=29, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(29)]),
        ),
        migrations.CreateModel(
            name='EVPNEthernetSegmentLAGInterface',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dcim.device')),
                ('esi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nautobot_plugin_evpn.evpnethernetsegment')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dcim.interface')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'EVPN ESI-LAG',
                'verbose_name_plural': 'EVPN ESI-LAGs',
                'ordering': ['esi'],
            },
            bases=(models.Model, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin),
        ),
    ]
